apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Mi App</title>
    </head>
    <body>
      <h1>Frontend funcionando 🚀</h1>
      <button onclick="callBackend()">Llamar backend</button>
      <p id="result"></p>

      <script>
        function callBackend() {
          fetch('http://backend')
            .then(res => res.text())
            .then(data => {
              document.getElementById("result").innerText = data;
            })
            .catch(err => {
              document.getElementById("result").innerText = "Error: " + err;
            });
        }
      </script>
    </body>
    </html>